language: node_js
dist: trusty
sudo: false

node_js:
  - node

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - bdxhost/node_modules
    - bdxhost/app/node_modules
    - bdxhost/flow-typed

addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main'
      - sourceline: 'deb https://dl.winehq.org/wine-builds/ubuntu/ trusty main'
    packages:
      - libstdc++6
      - dotnet-sdk-2.1
      - winehq-stable

install:
  - cd bdxhost
  - yarn
  - cd app
  - yarn
  - cd ..

jobs:
  include:
    - name: lint
      script: yarn lint

    - name: package
      script: yarn package
