language: node_js

node_js:
  - node

addons:
  apt:
    update: true
    sources:
      - packages-microsoft-prod: https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
    packages:
      - dotnet-sdk-2.1

cache:
  yarn: true
  directories:
    - bdxhost/node_modules
    - bdxhost/app/node_modules

install:
  - cd bdxhost
  - yarn
  - cd app && yarn && cd ..

script:
  - cd bdxhost
  - yarn lint
  - yarn package
