language: node_js

node_js:
  - node

cache:
  yarn: true
  directories:
    - bdxhost/node_modules
    - bdxhost/app/node_modules

before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install dotnet-runtime-2.1 aspnetcore-runtime-2.1 dotnet-sdk-2.1

install:
  - cd bdxhost
  - yarn
  - cd app && yarn

script:
  - cd bdxhost
  - yarn lint
  - yarn release
